config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  resources :activities
  resources :courses
  resources :resumes, only: [:index, :new, :create, :destroy]
  root 'home#index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   mount Rapidfire::Engine => "/rapidfire"
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  has_many :questions
  belongs_to :UserCourse
  has_one :resume
  cattr_accessor :current_user
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :user_courses
	has_many :activities
	cattr_accessor :current_user
end

app/models/course_activity.rb
class CourseActivity < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :activity
end

app/models/resume.rb
class Resume < ActiveRecord::Base
	belongs_to :resume
   mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :users
  has_many :user_courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :authentication_keys => [:matricula]


  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	belongs_to :User
	belongs_to :Course
	has_many :Activities
end

app/controllers/activities_controller.rb
class ActivitiesController < InheritedResources::Base
before_action :authenticate_user!
	def index
		@activities = Activity.where("user_id = ?", current_user)
	end
   def create
      @activity = Activity.new(activity_params)
      
      if @activity.save
         redirect_to rapidfire_path
      end
      
   end
    def can_administer?
      if current_user.isProfessor?
      	true
      else
      	false
      end
    end
	private
		def activity_params
		  params.require(:activity).permit(:name, :chapter, :instruction, :desc, :attachments, :user_id, :course_id)
		end
	end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def set_current_user
  	Course.current_user = current_user
  	Activity.current_user = current_user
  end
  def can_administer?
    current_user.try(:isProfessor?)
  end
end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
before_action :authenticate_user!
	def index
		@cursos = UserCourse.where("user_id = ?", current_user)
	end
  	def show
  		@course = Course.find(params[:id])
  		@activities = Activity.where("course_id = ?", @course.id)
  	end
  private
    def course_params
      params.require(:course).permit(:course, :c_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	/@usr = current_user/
  	if user_signed_in?
  		@cursos = UserCourse.where("user_id = ?", current_user)
  	else
  		redirect_to new_user_session_url
  	end
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
   before_action :authenticate_user!
   def index
      @resumes = Resume.all
   end
   
   def new
      @resume = Resume.new
   end
   
   def create
      @resume = Resume.new(resume_params)
      
      if @resume.save
         redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
      else
         render "new"
      end
      
   end
   
   def destroy
      @resume = Resume.find(params[:id])
      @resume.destroy
      redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
   end
   
   private
      def resume_params
      params.require(:resume).permit(:name, :attachment)
   end
   
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/activities/_form.html.erb
<% if current_user.isProfessor? %>
  <br><br>
  <div class="container">
    <div class="container">
      <div class="container">
        <div class="card">
          <div class="container">
          <div class="icon-block">
            <h2 class="center blue-text"><i class="material-icons">work</i></h2>
            <h5 class="center">Nueva actividad</h5>
            <li class="divider"></li>
            <%= form_for(@activity) do |f| %>
              <% if @activity.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

                  <ul>
                  <% @activity.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="field">
                <p class="teal-text text-lighten-2">Título</p>
                <%= f.text_field :name %>
              </div>
              <div class="field">
                <p class="teal-text text-lighten-2">Capítulo</p>
                <%= f.text_field :chapter %>
              </div>
              <div class="field">
                <p class="teal-text text-lighten-2">Instrucciones</p>
                <%= f.text_area :instruction %>
              </div>
              <div class="field">
                <p class="teal-text text-lighten-2">Descripción</p>
                <%= f.text_field :desc %>
              </div>
              <div class="field">
                <p class="teal-text text-lighten-2">Archivos adjuntos</p>
                <%= f.select(:attachments, Resume.all.collect{|u| [u.name, u.id]}, {}, {:class => 'browser-default'}) %>
              <div class="field">
                <p class="teal-text text-lighten-2">Usuario</p>
                <%= f.select(:user_id, User.where("id = ?", current_user).collect{|u| [u.name, u.id]}, {}, {:class => 'browser-default'}) %>
              </div>
              <div class="field">
                <p class="teal-text text-lighten-2">Materia</p>
                <%= f.select(:course_id, Course.all.collect{|u| [u.c_name, u.id]}, {}, {:class => 'browser-default'}) %>
              </div>
              <br><br>
              <div class="actions">
                <button class="btn waves-effect waves-light" type="submit" name="action">Continuar
                <i class="material-icons right">send</i>
              </div>
              <br><br>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<% if current_user.isProfessor? %>
  <br><br>
  <div class="container">
    <div class="container">
      <div class="container">
        <div class="card">
          <div class="container">
          <div class="icon-block">
            <h2 class="center blue-text"><i class="material-icons">work</i></h2>
            <h5 class="center">Tareas</h5>
            <li class="divider"></li>
            <h5 class="center">Todos los cursos</h5>
            <% @activities.each do |activity| %>
            <tr>
              <li class="divider"></li>
              <h5 class="center">Detalles de la actividad</h5>
              <p class = "light">Título: <%= activity.name %></p>
              <p class="light">Capítulo: <%= activity.chapter %></p>
              <p class="light">Materia: <%= Course.find(activity.chapter).course %> | <%= Course.find(activity.chapter).c_name %></p>
              <li class="divider"></li>
              <br>
              <div class="row">
                <% if current_user.isProfessor? %>
                  <div class="center col s3"><%= link_to 'Seleccionar', activity %></div>
                  <div class="center col s3"><%= link_to "Ver archivos adjuntos", Resume.find(activity.attachments).attachment_url %></div>
                  <div class="center col s3"><%= link_to 'Editar', edit_activity_path(activity) %></div>
                  <div class="center col s3"><%= link_to 'Eliminar', activity, method: :delete, data: { confirm: 'Are you sure?' } %></div>
                <% else %>
                  <div class="center col s6"><%= link_to 'Seleccionar', activity %></div>
                  <div class="center col s6"><%= link_to "Ver archivos adjuntos", Resume.find(activity.attachments).attachment_url %></div>                  
                <% end %>
              </div>
          <% end %>
          <% if current_user.isProfessor? %>
            <li class="divider"></li>
            <div class="center col s12"><%= link_to 'Crear actividad', new_activity_path %></div>
          <% end %>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
<br><br>
<br><br>
<br><br>
<br><br>
  <h1 class="header center white-text">Forbidden</h1>
<% end %>

app/views/activities/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
  <br><br>
<div class="container">
    <div class="container">
      <div class="container">
        <div class="card">
          <div class="container">
            <p>
              <li class="divider"></li>
              <h5 class="center">Detalles de la actividad</h5>
              <p class = "light">Título: <%= @activity.name %></p>
              <p class="light">Capítulo: <%= @activity.chapter %></p>
              <p class="light">Materia: <%= Course.find(@activity.chapter).course %> | <%= Course.find(@activity.chapter).c_name %></p>
              <li class="divider"></li>
              <br>
            <% if current_user.isProfessor? %>
              <%= link_to 'Editar', edit_activity_path(@activity) %> |
              <%= link_to 'Atrás', activities_path %> |
              <%= link_to 'Más información ', rapidfire_path %>
              <br>
            <% else %>
              <a class="waves-effect waves-light btn" href="/rapidfire">Responder actividad</a>
            <% end %>
          </div>
          <br>
        </div>
      </div>
    </div>
  </div>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p class="teal-text text-lighten-2">Clave</p>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <p class="teal-text text-lighten-2">Nombre de la Materia</p>
    <%= f.text_field :c_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <div class="container">
        <div class="container">
          <div class="card">
            <div class="container">
            <div class="icon-block">
            <h2 class="center blue-text"><i class="material-icons">assignment</i></h2>
            <h5 class="center">Mis Cursos</h5>
              <table>
                  <tbody>
                    <% @cursos.each do|course|%>
                    <tr>
                      <li class="divider"></li>
                      <td><%= Course.find(course.course_id).c_name %></td>
                      <td><%= Course.find(course.course_id).course %></td>
                      <td><%= link_to 'Ir', Course.find(course.course_id) %></td>
                    </tr>
                    <%end%>
                </tbody>
              </table>

<br>
</div>
</div>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<br><br>
  <div class="container">
    <div class="container">
      <div class="container">
        <div class="card">
          <div class="container">
          <div class="icon-block">
            <h2 class="center blue-text"><i class="material-icons">work</i></h2>
            <h5 class="center">Tareas</h5>
            <li class="divider"></li>
            <h5 class="center"><%= @course.c_name %></h5>
            <% @activities.each do |activity| %>
			      <tr>
              <li class="divider"></li>
			        <h5 class="center"><%= activity.name %></h5>
              <p class = "center light"></p>
			        <p class="center light"><%= activity.instruction %></p>
              <li class="divider"></li>
              <br>
              <div class="row">
                <% if current_user.isProfessor? %>
                  <div class="center col s3"><%= link_to "Ver archivos adjuntos", Resume.find(activity.attachments).attachment_url %></div>
                  <div class="center col s3"><%= link_to 'Seleccionar', activity %></div>
                  <div class="center col s3"><%= link_to 'Editar', edit_activity_path(activity) %></div>
                  <div class="center col s3"><%= link_to 'Eliminar', activity, method: :delete, data: { confirm: 'Are you sure?' } %></div>
                <% else %>
                  <div class="center col s6"><%= link_to "Ver archivos adjuntos", Resume.find(activity.attachments).attachment_url %></div>
                  <div class="center col s6"><%= link_to 'Seleccionar', activity %></div
                <% end %>
                <li class="divider"></li>
              </div>
			    <% end %>
          <% if current_user.isProfessor? %>
            <li class="divider"></li>
            <div class="center col s12"><%= link_to 'Crear actividad', new_activity_path %></div>
          <% end %>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <div class="container">
        <div class="container">
          <div class="card">
            <div class="container">
            <div class="icon-block">
            <h2 class="center blue-text"><i class="material-icons">assignment</i></h2>
            <h5 class="center">Mis Cursos</h5>
                <table>
                  <tbody>
                  <% @cursos.each do|course|%>
                    <tr>
                      <li class="divider"></li>
                      <td><%= Course.find(course.course_id).c_name %></td>
                      <td><%= Course.find(course.course_id).course %></td>
                      <td><%= link_to 'Ir', Course.find(course.course_id) %></td>
                    </tr>
                  <%end%>
                  </tbody>
                </table>
                <br>
              </div>
          </div>
      </div>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Dashboard</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <footer class="page-footer orange">
                <div class="footer-copyright">
                    <h6 class="white-text center">[BETA VERSION] D.R.© Instituto Tecnológico y de Estudios Superiores de Monterrey, Eugenio Garza Sada 2501 Sur, Col. Tecnológico, Monterrey, N.L. México. 2016 [BETA VERSION]</h6>
                    <br>
                </div>
    </footer>
  </body>
</html>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Dashboard</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<% if user_signed_in? %>
  <ul id="dropdown1" class="dropdown-content">
                <li>
                  <%= link_to 'Salir', '/users/sign_out', :method => :delete %>
                </li>
        </ul>
        <div class="navbar-fixed">
        <nav class="blue lighten-1" role="navigation">
            <div class="nav-wrapper">
                <a id="logo-container" href="/" class="brand-logo"><img style="border: none;" src="/icon.png" alt="Home"/></a>
                            <ul class="right hide-on-med-and-down">
                                  <%if current_user.isProfessor? %>
                                    <li><a href="/activities">Actividades<i class="material-icons left">work</i></a></li>
                                    <li><a href="/resumes">Archivos<i class="material-icons left">attachment</i></a></li>
                                  <%end%>
                                  <li><a href="/courses">Cursos<i class="material-icons left">assignment</i></a></li>
                                  <li><a class="dropdown-button" data-beloworigin="true" data-hover="true" href="#" data-activates="dropdown1">Hola, <%=current_user.name %><i class="material-icons left">person</i><i class="material-icons right">arrow_drop_down</i></a></li>
                             </ul>
                            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
                        </div>
                    <ul id="nav-mobile" class="side-nav">
                      <li>
                    <div class="row center">
                      <p><a class="blue-text text-lighten-1">Hola, <%=current_user.name %><i class="material-icons left">perm_identity</i></a></p>
                    </div>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <div class="row center">
                          <a class="blue-text text-lighten-1" href="/courses">Cursos<i class="material-icons left">assignment</i></a>
                        </div>
                      </li>
                      <%if current_user.isProfessor? %>
                        <li class="divider"></li>
                        <li>
                          <div class="row center">
                            <a class="blue-text text-lighten-1" href="/activities">Actividades<i class="material-icons left">work</i></a>
                          </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                          <div class="row center">
                            <a class="blue-text text-lighten-1" href="/resumes">Archivos<i class="material-icons left">attachment</i></a>
                          </div>
                        </li>
                      <% end %>
                      <li class="divider"></li>
                      <li>
                      <div class="row center">
                        <%= link_to '<p class="blue-text text-lighten-1">Salir<i class="material-icons left">input</i></p>'.html_safe, '/users/sign_out', :method => :delete %>
                        </div>
                      </li>
        </ul>
      </div>
  </nav>
  <% end %>
  </body>
  </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tec de Monterrey | Ortografía</title>
  <%= stylesheet_link_tag    'materialize', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
	<body>
		<body background="/background.jpg">
		<%= render 'layouts/navbar'%>
		<main>
			<%= yield %>
		</main>
	</body>
	<%= render 'layouts/footer'%>

app/views/rapidfire/answer_groups/new.html.erb
  <br><br>
  <div class="container">
    <div class="container">
      <div class="container">
        <div class="card">
          <div class="container">
          <div class="icon-block">
            <h2 class="center blue-text"><i class="material-icons">work</i></h2>
            <h5 class="center">Responda correctamente las siguientes preguntas</h5>
            <li class="divider"></li>
              <%= form_for([@question_group, @answer_group_builder]) do |f| %>
                    <%- @answer_group_builder.answers.each do |answer| %><br>
                      <div class="row">
                        <div class="input-field">
                          <%= f.fields_for("#{answer.question.id}", answer) do |answer_form| %>
                            <%= render_answer_form_helper(answer, answer_form) %>
                          </div>
                        </div>
                      <% end %>
                      <br>
                    <% end %>
                  <div class="row">
                    <button class="btn waves-effect waves-light" type="send" name="action">Terminar
                  <i class="material-icons right">send</i>
              </button>
              <% end %>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
</div>

app/views/rapidfire/answer_groups/new.html.haml
%h2 Please answer these Questions
%hr

= simple_form_for([@question_group, @answer_group_builder]) do |f|
  - @answer_group_builder.answers.each do |answer|
    = f.simple_fields_for "#{answer.question.id}", answer do |answer_form|
      = render_answer_form_helper(answer, answer_form)
  = f.submit "Save", class: "btn btn-primary btn-large"

app/views/rapidfire/answers/_checkbox.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.fields_for :answer_text do |af| %>
<%= f.label :answer_text, answer.question.question_text %>
  <%- answer.question.options.each do |option| %>
    
      <%= af.check_box nil, { id: nil, checked: checkbox_checked?(answer, option) }, option %>
      <%= af.label option do %>
      <%= option %>
    <% end %>
  <% end %>
<% end %>

app/views/rapidfire/answers/_checkbox.html.haml
= f.input :answer_text, as: :check_boxes, collection: answer.question.options,
  label: answer.question.question_text, checked: answer.answer_text.try(:split, ",")

app/views/rapidfire/answers/_date.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%= f.text_field :answer_text %>

app/views/rapidfire/answers/_date.html.haml
= f.input :answer_text, as: :string, label: answer.question.question_text

app/views/rapidfire/answers/_errors.html.erb
<%- if answer.errors.any? %>
  <ul>
    <%- answer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/rapidfire/answers/_long.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%= f.text_area :answer_text, :rows => 5 %>

app/views/rapidfire/answers/_long.html.haml
= f.input :answer_text, as: :text, label: answer.question.question_text,
  input_html: { rows: 5 }

app/views/rapidfire/answers/_numeric.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%= f.text_field :answer_text %>

app/views/rapidfire/answers/_numeric.html.haml
= f.input :answer_text, as: :string, label: answer.question.question_text

app/views/rapidfire/answers/_radio.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>
<%- answer.question.options.each do |option| %>
    <%= f.radio_button :answer_text, option %>
    <%= f.label "answer_text_#{option}", option do %>
    <%= option %>
  <% end %>
<% end %>
<%= f.label :answer_text, answer.question.question_text %>

app/views/rapidfire/answers/_select.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>


<%= f.select :answer_text, answer.question.options, include_blank: true %>
<%= f.label :answer_text, answer.question.question_text %>

app/views/rapidfire/answers/_select.html.haml
= f.input :answer_text, collection: answer.question.options, include_blank: true,
  label: answer.question.question_text, prompt: "Please select"

app/views/rapidfire/answers/_short.html.erb
<%= render partial: "rapidfire/answers/errors", locals: {answer: answer} %>

<%= f.label :answer_text, answer.question.question_text %>
<%= f.text_field :answer_text %>

app/views/rapidfire/answers/_short.html.haml
= f.input :answer_text, as: :string, label: answer.question.question_text

app/views/rapidfire/question_groups/_form.html.erb
  <br><br>
  <div class="container">
    <div class="container">
      <div class="container">
        <div class="card">
          <div class="container">
          <div class="icon-block">
          <br>
            <h2 class="center blue-text"><i class="medium material-icons">bookmark</i></h2>
            <h5 class="center">Nueva sección</h5>
            <li class="divider"></li>

              <%= form_for question_group do |f| %>
                <%- if question_group.errors.any? %>
                  <ul>
                    <%- question_group.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                <% end %>

                <p class="teal-text text-lighten-2">Nombre de la Sección</p>
                <%= f.text_field :name%>
                <p class="teal-text text-lighten-2">Actividad</p>
                <%= f.select(:activity_id, Activity.all.collect{|u| [u.name, u.id]}, {}, {:class => 'browser-default'}) %>
                <br>
                <div class="actions">
                  <button class="btn waves-effect waves-light" type="submit" name="action">Continuar
                  <i class="material-icons right">send</i></button>
                </div>
                <br>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/rapidfire/question_groups/_form.html.haml
%h3= question_group.new_record? ? "New Survey" : "Edit Survey"

= simple_form_for question_group do |f|
  = f.input :name
  = f.submit "Save", class: "btn btn-primary"

app/views/rapidfire/question_groups/_html_results.html.haml
- results.each do |result|
  %div
    %h4
      Question:
      = result.question.question_text
    %p
      - if result.results.is_a?(Array)
        %ol
          - result.results.each do |answer|
            %li= answer
      - elsif result.results.is_a?(Hash)
        %table.table.table-striped.table-bordered
          %thead
            %tr
              %th Option
              %th Count
          %tbody
            - result.results.each do |option, count|
              %tr
                %td= option
                %td= count
  %hr

app/views/rapidfire/question_groups/_json_results.html.haml
#js-json-results

:javascript
  var charts = new ResultChart("#{question_group.id}");
  charts.render();

app/views/rapidfire/question_groups/_question_group.html.erb
<tr id= "question_group_<%= question_group.id %>">
  <td>
    <% if can_administer? %>
      <%= link_to question_group.name, question_group_questions_path(question_group) %>
    <% else %>
      <%= question_group.name %>
    <% end %>
  </td>
  <td>
    <ul class="horizontal-list">
      <li><%= link_to "Responder Actividad", new_question_group_answer_group_path(question_group) %></li>
      <% if can_administer? %>
        <li><%= link_to "Entrega de estudiantes", [:results, question_group] %></li>
        <li><%= link_to "Eliminar", [question_group], method: :delete %></li>
      <% end %>
    </ul>
  </td>
</tr>

app/views/rapidfire/question_groups/destroy.js.haml
$("#question_group_#{@question_group.id}").remove();

app/views/rapidfire/question_groups/index.html.haml
%h2
  Surveys
  - if can_administer?
    .pull-right
      = link_to "New Survey", new_question_group_path, class: "btn btn-primary"
%hr

%table.table.table-striped.table-bordered
  %colgroup
    %col
    %col{ width: "45%" }
  %thead
    %tr
      %th Survey
      %th
  %tbody
    = render partial: "question_group", collection: @question_groups

app/views/rapidfire/questions/destroy.js.haml
$("#question_#{@question.id}").remove();

app/views/resumes/index.html.erb
<% if current_user.isProfessor? %>
  <br><br>
  <div class="container">
    <div class="container">
      <div class="container">
        <div class="card">
          <div class="container">
          <div class="icon-block">
            <br>
            <h2 class="center blue-text"><i class="medium material-icons">attachment</i></h2>
            <h5 class="center">Archivos</h5>
            <li class="divider"></li>
<br />
<div class="row center">
<%= link_to "Subir nuevo archivo", new_resume_path, class: "btn btn-primary" %></div>
<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Nombre del archivo</th>
         <th></th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @resumes.each do |resume| %>
         
         <tr>
            <td><%= resume.name %></td>
            <td><%= link_to "Ver", resume.attachment_url %></td>
            <td><%= button_to "Eliminar",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>
</div>
</div>
</div>
</div>
</div>
</div>
<% end %>